# Synopsis: My guardrails baseline
apiVersion: github.com/microsoft/PSRule/v1
kind: Baseline
metadata:
  name: My.Guardrails1
  annotations:
    obsolete: False
spec:
  rule:
    include:
    # PSRule.Rules.Azure
    ## Template rules 'https://azure.github.io/PSRule.Rules.Azure/en/rules/Azure.Template.DebugDeployment/'
    - Azure.Template.DebugDeployment
    - Azure.Template.DefineParameters
    - Azure.Template.ExpressionLength
    - Azure.Template.LocationDefault
    - Azure.Template.LocationType
    - Azure.Template.MetadataLink
    - Azure.Template.ParameterDataTypes
    - Azure.Template.ParameterFile
    - Azure.Template.ParameterMetadata
    - Azure.Template.ParameterMinMaxValue
    - Azure.Template.ParameterScheme
    - Azure.Template.ParameterStrongType
    - Azure.Template.ParameterValue
    - Azure.Template.ResourceLocation
    - Azure.Template.Resources
    - Azure.Template.TemplateFile
    - Azure.Template.TemplateSchema
    - Azure.Template.TemplateScheme
    - Azure.Template.UseComments
    - Azure.Template.UseDescriptions
    - Azure.Template.UseLocationParameter
    - Azure.Template.UseParameters
    - Azure.Template.UseVariables
    - Azure.Template.ValidSecretRef
    ## Deployment rules 'https://azure.github.io/PSRule.Rules.Azure/en/rules/Azure.Deployment.AdminUsername/'
    - Azure.Deployment.AdminUsername
    - Azure.Deployment.Name
    - Azure.Deployment.OuterSecret
    - Azure.Deployment.OutputSecretValue
    - Azure.Deployment.SecureParameter
    - Azure.Deployment.SecureValue
    ## My Guardrails
    - My.Resource.MandatoryTags
    - Guardrails-000.Policy.231f0045f18f
    includeLocal: true
