# Synopsis: My guardrails baseline
apiVersion: github.com/microsoft/PSRule/v1
kind: Baseline
metadata:
  name: My.Guardrails3
  annotations:
    obsolete: False
spec:
  rule:
    exclude:
    - Azure.ACR.Usage
    - Azure.ACR.ContainerScan
    - Azure.ACR.ImageHealth
    - Azure.ACR.GeoReplica
    - Azure.ADX.Usage
    - Azure.AKS.Version
    - Azure.AKS.PoolVersion
    - Azure.AKS.PoolScaleSet
    - Azure.AKS.NodeMinPods
    - Azure.AKS.AutoScaling
    - Azure.AKS.CNISubnetSize
    - Azure.AKS.AvailabilityZone
    - Azure.AKS.AuditLogs
    - Azure.AKS.PlatformLogs
    - Azure.AKS.UptimeSLA
    - Azure.AKS.EphemeralOSDisk
    - Azure.APIM.HTTPEndpoint
    - Azure.APIM.APIDescriptors
    - Azure.APIM.HTTPBackend
    - Azure.APIM.EncryptValues
    - Azure.APIM.ProductSubscription
    - Azure.APIM.ProductApproval
    - Azure.APIM.SampleProducts
    - Azure.APIM.ProductDescriptors
    - Azure.APIM.ProductTerms
    - Azure.APIM.CertificateExpiry
    - Azure.APIM.AvailabilityZone
    - Azure.APIM.MinAPIVersion
    - Azure.APIM.MultiRegion
    - Azure.APIM.MultiRegionGateway
    - Azure.APIM.CORSPolicy
    - Azure.APIM.PolicyBase
    - Azure.AppConfig.AuditLogs
    - Azure.AppConfig.PurgeProtect
    - Azure.AppGw.UseHTTPS
    - Azure.AppGw.AvailabilityZone
    - Azure.AppGw.Name
    - Azure.AppService.PlanInstanceCount
    - Azure.AppService.MinTLS
    - Azure.AppService.RemoteDebug
    - Azure.AppService.NETVersion
    - Azure.AppService.PHPVersion
    - Azure.AppService.AlwaysOn
    - Azure.AppService.HTTP2
    - Azure.AppService.WebProbe
    - Azure.AppService.WebProbePath
    - Azure.AppService.WebSecureFtp
    - Azure.ASE.MigrateV3
    - Azure.Automation.EncryptVariables
    - Azure.Automation.WebHookExpiry
    - Azure.Automation.AuditLogs
    - Azure.Automation.PlatformLogs
    - Azure.CDN.EndpointName
    - Azure.CDN.MinTLS
    - Azure.CDN.UseFrontDoor
    - Azure.ContainerApp.RestrictIngress
    - Azure.Cosmos.DefenderCloud
    # - Azure.Deployment.OutputSecretValue
    # - Azure.Deployment.AdminUsername
    # - Azure.Deployment.SecureValue
    # - Azure.Deployment.OuterSecret
    - Azure.EventHub.Usage
    - Azure.FrontDoor.MinTLS
    - Azure.FrontDoor.Logs
    - Azure.FrontDoor.Probe
    - Azure.FrontDoor.ProbeMethod
    - Azure.FrontDoor.ProbePath
    - Azure.FrontDoor.UseWAF
    - Azure.FrontDoor.UseCaching
    - Azure.KeyVault.AccessPolicy
    - Azure.KeyVault.Logs
    - Azure.KeyVault.Name
    - Azure.KeyVault.SecretName
    - Azure.KeyVault.KeyName
    - Azure.KeyVault.AutoRotationPolicy
    - Azure.KeyVault.Firewall
    - Azure.LB.Probe
    - Azure.LB.AvailabilityZone
    - Azure.LB.StandardSKU
    - Azure.LogicApp.LimitHTTPTrigger
    - Azure.MariaDB.DefenderCloud
    - Azure.MariaDB.UseSSL
    - Azure.MariaDB.MinTLS
    - Azure.MariaDB.ServerName
    - Azure.MariaDB.DatabaseName
    - Azure.MariaDB.FirewallRuleName
    - Azure.MariaDB.VNETRuleName
    - Azure.MariaDB.AllowAzureAccess
    - Azure.MariaDB.FirewallRuleCount
    - Azure.MariaDB.FirewallIPRange
    - Azure.MySQL.FirewallRuleCount
    - Azure.MySQL.AllowAzureAccess
    - Azure.MySQL.FirewallIPRange
    - Azure.MySQL.ServerName
    - Azure.MySQL.GeoRedundantBackup
    - Azure.MySQL.UseFlexible
    - Azure.MySQL.DefenderCloud
    - Azure.MySQL.AAD
    - Azure.MySQL.AADOnly
    - Azure.NSG.AnyInboundSource
    - Azure.NSG.DenyAllInbound
    - Azure.NSG.LateralTraversal
    - Azure.NSG.Associated
    - Azure.Policy.Descriptors
    - Azure.Policy.AssignmentDescriptors
    - Azure.Policy.AssignmentAssignedBy
    - Azure.Policy.ExemptionDescriptors
    - Azure.Policy.WaiverExpiry
    - Azure.PostgreSQL.FirewallRuleCount
    - Azure.PostgreSQL.AllowAzureAccess
    - Azure.PostgreSQL.FirewallIPRange
    - Azure.PostgreSQL.ServerName
    - Azure.PostgreSQL.GeoRedundantBackup
    - Azure.PostgreSQL.DefenderCloud
    - Azure.PostgreSQL.AAD
    - Azure.PublicIP.IsAttached
    - Azure.PublicIP.Name
    - Azure.PublicIP.DNSLabel
    - Azure.PublicIP.AvailabilityZone
    - Azure.Redis.MaxMemoryReserved
    - Azure.Redis.AvailabilityZone
    - Azure.RedisEnterprise.Zones
    - Azure.Redis.FirewallRuleCount
    - Azure.Redis.FirewallIPRange
    - Azure.Redis.Version
    - Azure.Resource.UseTags
    - Azure.Resource.AllowedRegions
    - Azure.ResourceGroup.Name
    - Azure.RSV.StorageType
    - Azure.RSV.ReplicationAlert
    - Azure.Search.SKU
    - Azure.Search.QuerySLA
    - Azure.Search.IndexSLA
    - Azure.Search.ManagedIdentity
    - Azure.Search.Name
    - Azure.ServiceBus.Usage
    - Azure.ServiceBus.MinTLS
    - Azure.ServiceBus.AuditLogs
    - Azure.ServiceFabric.AAD
    - Azure.SignalR.Name
    - Azure.SQL.FirewallRuleCount
    - Azure.SQL.AllowAzureAccess
    - Azure.SQL.FirewallIPRange
    - Azure.SQL.DefenderCloud
    - Azure.SQL.Auditing
    - Azure.SQL.AAD
    - Azure.SQL.ServerName
    - Azure.SQL.AADOnly
    - Azure.SQL.TDE
    - Azure.SQL.DBName
    - Azure.SQL.FGName
    - Azure.SQLMI.Name
    - Azure.SQLMI.AADOnly
    - Azure.SQLMI.AAD
    - Azure.Storage.UseReplication
    - Azure.Storage.SoftDelete
    - Azure.Storage.BlobAccessType
    - Azure.Storage.Name
    - Azure.Storage.FileShareSoftDelete
    - Azure.Storage.ContainerSoftDelete
    - Azure.Storage.DefenderCloud
    - Azure.RBAC.UseGroups
    - Azure.RBAC.LimitOwner
    - Azure.RBAC.LimitMGDelegation
    - Azure.RBAC.CoAdministrator
    - Azure.RBAC.UseRGDelegation
    - Azure.RBAC.PIM
    - Azure.DefenderCloud.Contact
    - Azure.DefenderCloud.Provisioning
    - Azure.Monitor.ServiceHealth
    # - Azure.Template.TemplateFile
    # - Azure.Template.TemplateSchema
    # - Azure.Template.TemplateScheme
    # - Azure.Template.ParameterMetadata
    # - Azure.Template.Resources
    # - Azure.Template.UseParameters
    # - Azure.Template.DefineParameters
    # - Azure.Template.UseVariables
    # - Azure.Template.LocationDefault
    # - Azure.Template.LocationType
    # - Azure.Template.ResourceLocation
    # - Azure.Template.UseLocationParameter
    # - Azure.Template.ParameterMinMaxValue
    # - Azure.Template.DebugDeployment
    # - Azure.Template.ParameterDataTypes
    # - Azure.Template.ParameterStrongType
    # - Azure.Template.ExpressionLength
    # - Azure.Template.ParameterFile
    # - Azure.Template.ParameterScheme
    # - Azure.Template.MetadataLink
    # - Azure.Template.ParameterValue
    # - Azure.Template.ValidSecretRef
    # - Azure.Template.UseComments
    # - Azure.Template.UseDescriptions
    - Azure.TrafficManager.Endpoints
    - Azure.TrafficManager.Protocol
    - Azure.VM.UseManagedDisks
    - Azure.VM.DiskCaching
    - Azure.VM.UseHybridUseBenefit
    - Azure.VM.AcceleratedNetworking
    - Azure.VM.PublicKey
    - Azure.VM.Agent
    - Azure.VM.Updates
    - Azure.VM.Name
    - Azure.VM.ComputerName
    - Azure.VM.DiskAttached
    - Azure.VM.DiskSizeAlignment
    - Azure.VM.ADE
    - Azure.VM.DiskName
    - Azure.VM.ASMinMembers
    - Azure.VM.ASName
    - Azure.VM.NICAttached
    - Azure.VM.NICName
    - Azure.VM.PPGName
    - Azure.VM.ScriptExtensions
    - Azure.VM.MigrateAMA
    - Azure.VM.SQLServerDisk
    - Azure.VM.AMA
    - Azure.VMSS.Name
    - Azure.VMSS.ComputerName
    - Azure.VMSS.PublicKey
    - Azure.VMSS.ScriptExtensions
    - Azure.VMSS.MigrateAMA
    - Azure.VMSS.AMA
    - Azure.VNET.UseNSGs
    - Azure.VNET.SingleDNS
    - Azure.VNET.LocalDNS
    - Azure.VNET.PeerState
    - Azure.VNET.SubnetName
    - Azure.VNET.BastionSubnet
    - Azure.VNET.FirewallSubnet
    - Azure.VNG.VPNLegacySKU
    - Azure.VNG.VPNActiveActive
    - Azure.VNG.ERLegacySKU
    - Azure.VNG.VPNAvailabilityZoneSKU
    - Azure.VNG.ERAvailabilityZoneSKU
    - Azure.ACR.AdminUser
    - Azure.ACR.MinSku
    - Azure.ACR.Name
    - Azure.ACR.ContentTrust
    - Azure.ACR.Firewall
    - Azure.ADX.ManagedIdentity
    - Azure.ADX.DiskEncryption
    - Azure.ADX.SLA
    - Azure.AKS.MinNodeCount
    - Azure.AKS.ManagedIdentity
    - Azure.AKS.StandardLB
    - Azure.AKS.NetworkPolicy
    - Azure.AKS.AzurePolicyAddOn
    - Azure.AKS.ManagedAAD
    - Azure.AKS.AuthorizedIPs
    - Azure.AKS.LocalAccounts
    - Azure.AKS.AzureRBAC
    - Azure.AKS.SecretStore
    - Azure.AKS.SecretStoreRotation
    - Azure.AKS.HttpAppRouting
    - Azure.AKS.AutoUpgrade
    - Azure.AKS.UseRBAC
    - Azure.AKS.Name
    - Azure.AKS.DNSPrefix
    - Azure.AKS.ContainerInsights
    - Azure.AKS.DefenderProfile
    - Azure.APIM.ManagedIdentity
    - Azure.APIM.Protocols
    - Azure.APIM.Ciphers
    - Azure.APIM.Name
    - Azure.AppConfig.SKU
    - Azure.AppConfig.Name
    - Azure.AppConfig.DisableLocalAuth
    - Azure.AppGw.MinInstance
    - Azure.AppGw.MinSku
    - Azure.AppGw.UseWAF
    - Azure.AppGw.SSLPolicy
    - Azure.AppGw.Prevention
    - Azure.AppGw.WAFEnabled
    - Azure.AppGw.OWASP
    - Azure.AppGw.WAFRules
    - Azure.AppGw.MigrateV2
    - Azure.AppGwWAF.Enabled
    - Azure.AppGwWAF.PreventionMode
    - Azure.AppGwWAF.Exclusions
    - Azure.AppGwWAF.RuleGroups
    - Azure.AppInsights.Workspace
    - Azure.AppInsights.Name
    - Azure.AppService.MinPlan
    - Azure.AppService.ManagedIdentity
    - Azure.AppService.ARRAffinity
    - Azure.AppService.UseHTTPS
    - Azure.ASG.Name
    - Azure.Automation.ManagedIdentity
    - Azure.Bastion.Name
    - Azure.BV.Immutable
    - Azure.CDN.HTTP
    - Azure.Cognitive.PublicAccess
    - Azure.Cognitive.ManagedIdentity
    - Azure.Cognitive.DisableLocalAuth
    - Azure.Cognitive.PrivateEndpoints
    - Azure.ContainerApp.Insecure
    - Azure.ContainerApp.ManagedIdentity
    - Azure.ContainerApp.Name
    - Azure.ContainerApp.PublicAccess
    - Azure.ContainerApp.ExternalIngress
    - Azure.ContainerApp.Storage
    - Azure.ContainerApp.DisableAffinity
    - Azure.ContainerApp.APIVersion
    - Azure.Cosmos.DisableMetadataWrite
    - Azure.Cosmos.AccountName
    - Azure.Databricks.SecureConnectivity
    - Azure.DataFactory.Version
    - Azure.Defender.Containers
    - Azure.Defender.Servers
    - Azure.Defender.SQL
    - Azure.Defender.AppServices
    - Azure.Defender.Storage
    - Azure.Defender.SQLOnVM
    - Azure.Defender.KeyVault
    - Azure.Defender.Dns
    - Azure.Defender.Arm
    - Azure.Defender.Cspm
    - Azure.Defender.CosmosDb
    - Azure.Defender.OssRdb
    # - Azure.Deployment.Name
    - Azure.EventGrid.TopicPublicAccess
    - Azure.EventGrid.ManagedIdentity
    - Azure.EventGrid.DisableLocalAuth
    - Azure.EventHub.DisableLocalAuth
    - Azure.EventHub.MinTLS
    - Azure.Firewall.Name
    - Azure.Firewall.PolicyName
    - Azure.Firewall.Mode
    - Azure.Firewall.PolicyMode
    - Azure.FrontDoor.State
    - Azure.FrontDoor.Name
    - Azure.FrontDoor.WAF.Mode
    - Azure.FrontDoor.WAF.Enabled
    - Azure.FrontDoor.WAF.Name
    - Azure.FrontDoor.ManagedIdentity
    - Azure.FrontDoorWAF.Enabled
    - Azure.FrontDoorWAF.PreventionMode
    - Azure.FrontDoorWAF.Exclusions
    - Azure.FrontDoorWAF.RuleGroups
    - Azure.Identity.UserAssignedName
    - Azure.IoTHub.MinTLS
    - Azure.KeyVault.SoftDelete
    - Azure.KeyVault.PurgeProtect
    - Azure.KeyVault.RBAC
    - Azure.LB.Name
    - Azure.MariaDB.GeoRedundantBackup
    - Azure.MySQL.UseSSL
    - Azure.MySQL.MinTLS
    - Azure.NSG.Name
    - Azure.NSG.AKSRules
    - Azure.PostgreSQL.UseSSL
    - Azure.PostgreSQL.MinTLS
    - Azure.PostgreSQL.AADOnly
    - Azure.PrivateEndpoint.Name
    - Azure.PublicIP.StandardSKU
    - Azure.PublicIP.MigrateStandard
    - Azure.Redis.MinSKU
    - Azure.Redis.NonSslPort
    - Azure.Redis.MinTLS
    - Azure.Redis.PublicNetworkAccess
    - Azure.RedisEnterprise.MinTLS
    - Azure.Route.Name
    - Azure.RSV.Name
    - Azure.RSV.Immutable
    - Azure.ServiceBus.DisableLocalAuth
    - Azure.SignalR.ManagedIdentity
    - Azure.SignalR.SLA
    - Azure.SQL.MinTLS
    - Azure.SQLMI.ManagedIdentity
    - Azure.Storage.Firewall
    - Azure.Storage.MinTLS
    - Azure.Storage.SecureTransfer
    - Azure.Storage.BlobPublicAccess
    - Azure.VM.Standalone
    - Azure.VM.PromoSku
    - Azure.VM.BasicSku
    - Azure.VM.ASAlignment
    - Azure.VM.UniqueDns
    - Azure.VM.ShouldNotBeStopped
    - Azure.VNET.Name
    - Azure.VNG.Name
    - Azure.VNG.ConnectionName
    - Azure.vWAN.Name
    - Azure.WebPubSub.ManagedIdentity
    - Azure.WebPubSub.SLA
    include:
    # - Guardrails-000.Policy.*
    - My.Resource.MandatoryTags
    - Guardrails-000.Policy.231f0045f18f
    - Guardrails-000.Policy.9f15257d13f6
    - Guardrails-000.Policy.53dcd26ab338
    - Guardrails-000.Policy.c3fee06ded22
    - Guardrails-000.Policy.ad660e010347
    - Guardrails-000.Policy.10d77e99a8fd
    - Guardrails-000.Policy.3a6191b5112d
    - Guardrails-000.Policy.e92b23e64881
    - Guardrails-000.Policy.fde384278a9b
    - Guardrails-000.Policy.ffe24346cf1a
    - Guardrails-000.Policy.fcd05b3f0a55
    - Guardrails-000.Policy.0aca185d36fe
    - Guardrails-000.Policy.cb84a4c6acd9
    # PSRule.Rules.Azure
    ## Template rules 'https://azure.github.io/PSRule.Rules.Azure/en/rules/Azure.Template.DebugDeployment/'
    - Azure.Template.DebugDeployment
    - Azure.Template.DefineParameters
    - Azure.Template.ExpressionLength
    - Azure.Template.LocationDefault
    - Azure.Template.LocationType
    - Azure.Template.MetadataLink
    - Azure.Template.ParameterDataTypes
    - Azure.Template.ParameterFile
    - Azure.Template.ParameterMetadata
    - Azure.Template.ParameterMinMaxValue
    - Azure.Template.ParameterScheme
    - Azure.Template.ParameterStrongType
    - Azure.Template.ParameterValue
    - Azure.Template.ResourceLocation
    - Azure.Template.Resources
    - Azure.Template.TemplateFile
    - Azure.Template.TemplateSchema
    - Azure.Template.TemplateScheme
    - Azure.Template.UseComments
    - Azure.Template.UseDescriptions
    - Azure.Template.UseLocationParameter
    - Azure.Template.UseParameters
    - Azure.Template.UseVariables
    - Azure.Template.ValidSecretRef
    ## Deployment rules 'https://azure.github.io/PSRule.Rules.Azure/en/rules/Azure.Deployment.AdminUsername/'
    - Azure.Deployment.AdminUsername
    - Azure.Deployment.Name
    - Azure.Deployment.OuterSecret
    - Azure.Deployment.OutputSecretValue
    - Azure.Deployment.SecureParameter
    - Azure.Deployment.SecureValue
    includeLocal: true
